### ISSUE TITLE
Is tunneler host config ignored?

### ISSUE THREAD

**Issue by qrkourier** [openziti/ngx_ziti_module#1]
This module allows NGINX to bind Ziti services and proxy incoming requests that arrive via Ziti to Ziti-service-specific upstreams via the normal network i.e. underlay.

The module appears to override or ignore the tunneler `host.v1` config. I'd appreciate confirmation of understanding that there's no conflict with this module if a tunneler `host.v1` config happens to be present on the bound Ziti service. The hosting config is merely ignored because the Edge SDK implementation in this module is not a tunneler per se, correct?

**Comment by andrewpmartinez** [comment]
> The hosting config is merely ignored because the Edge SDK implementation in this module is not a tunneler per se, correct?

Correct! It does not attempt to integrate with host-level routing in any way that would enable the interception of IP/hostnames.

**Comment by qrkourier** [comment]
Right, interception would occur on the other side of the Ziti connection by which requests are arriving toward this module. I should have mentioned that I assume intercept configs have no bearing on the operation of this module because it is always "hosting," aka "terminating", never "intercepting," nor "dialing" a Ziti service.
