### ISSUE TITLE
Http queries to HTTP Server that is shutdown hang, no error response is received at the client 

### ISSUE THREAD

**Issue by dariuszSki** [openziti/ngx_ziti_module#3]
*Experienced*
Stopping the upstream target server after a connection was already made causes clients to sit thinking the connection was open.

*Expected*
If the target server is unreachable/stopped, close the connection.
If the target server has restarted, close existing connections and attempt to reconnect for new connections.

*Reproduction*
1) configure any `ziti` block for a target upstream server (i.e. HTTP Server)
2) connect to the target service via a different ziti client
3) stop the upstream server
4) attempt to use the service again from the client / observe

**Comment by dariuszSki** [comment]
error seen on the nginx side ```2022/12/07 16:53:52 [emerg] 55309#55328: connection with the upstream server failed```

**Comment by dariuszSki** [comment]
> _Experienced_ Stopping the upstream target server after a connection was already made causes clients to sit thinking the connection was open.
> 
> _Expected_ If the target server is unreachable/stopped, close the connection. If the target server has restarted, close existing connections and attempt to reconnect for new connections.
> 
> _Reproduction_
> 
> 1. configure any `ziti` block for a target upstream server (i.e. HTTP Server)
> 2. connect to the target service via a different ziti client
> 3. stop the upstream server
> 4. attempt to use the service again from the client / observe

@andrewpmartinez do you need anything else from me on this?

**Comment by andrewpmartinez** [comment]
I do not think so. I am looking at it now to see what is going on.
